export const AppText = {
  app: {
    name: "BasAaj",
    tagline: "Your everyday companion",
  },
  navbar: {
    searchPlaceholder: "Search for offers, stores, deals near you",
    defaultLocation: "Select Location",
    login: "Log in",
    signup: "Sign up",
  },
  location: {
    dialogTitle: "Choose your location",
    dialogSubtitle: "Select a delivery location to see deals and offers near you.",
    useCurrentLocation: "Use my current location",
    detecting: "Detecting your location...",
    searchPlaceholder: "Search for area, city, or pincode",
    popularCities: "Popular Cities",
    change: "Change",
    permissionDenied: "Location access denied. Please search manually.",
    errorFetching: "Could not detect location. Please search manually.",
  },
  hero: {
    title: "Discover Amazing Deals Near You",
    subtitle:
      "Find the best local deals, discounts, and offers from shops and businesses in your area.",
    cta: "Explore Now",
  },
  categories: [
    {
      label: "Electronics & Media",
      subcategories: ["Mobile Phones", "Laptops & Computers", "Cameras", "Audio & Headphones", "TV & Monitors", "Gaming"],
    },
    {
      label: "Home & Garden",
      subcategories: ["Furniture", "Home Decor", "Kitchen & Dining", "Lighting", "Garden & Outdoor", "Cleaning"],
    },
    {
      label: "Clothing, Shoes & Accessories",
      subcategories: ["Men's Clothing", "Women's Clothing", "Kids' Clothing", "Shoes & Footwear", "Watches & Jewellery", "Bags & Wallets"],
    },
    {
      label: "Baby & Kids",
      subcategories: ["Toys & Games", "Baby Gear", "Kids' Fashion", "School Supplies", "Feeding & Nursing"],
    },
    {
      label: "Vehicles",
      subcategories: ["Cars", "Bikes & Scooters", "Auto Accessories", "Spare Parts", "Car Care"],
    },
    {
      label: "Toys, Games & Hobbies",
      subcategories: ["Board Games", "Outdoor Play", "Collectibles", "Musical Instruments", "Art & Craft"],
    },
    {
      label: "Sports & Outdoors",
      subcategories: ["Gym & Fitness", "Cricket", "Football", "Cycling", "Camping & Hiking", "Yoga & Wellness"],
    },
    {
      label: "Collectibles & Art",
      subcategories: ["Paintings", "Antiques", "Coins & Stamps", "Sculptures", "Handmade Crafts"],
    },
    {
      label: "Pet Supplies",
      subcategories: ["Dog Supplies", "Cat Supplies", "Pet Food", "Pet Grooming", "Aquarium & Fish"],
    },
    {
      label: "More",
      subcategories: ["Books & Stationery", "Health & Beauty", "Food & Dining", "Services", "Entertainment"],
    },
  ],
  banners: [
    {
      image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=400&fit=crop",
      alt: "Exclusive deals near you",
    },
    {
      image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&h=400&fit=crop",
      alt: "Fashion sale up to 50% off",
    },
    {
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=400&fit=crop",
      alt: "Food & dining offers",
    },
  ],
  dashboardOffers: {
    title: "Offers Near You",
    offers: [
      {
        businessName: "Bistro 101",
        title: "Bistro 101 Lunch Buffet",
        description: "Enjoy a lavish spread of continental and asian cuisines with unlimited soft drinks.",
        originalPrice: 2500,
        discountedPrice: 1500,
        discount: "Flat 40% OFF",
        validity: "Feb 15 - Mar 15, 2026",
        location: "Lower Parel",
        distance: "0.8 km",
        phone: "+91-98765-43210",
        views: 1200,
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
      },
      {
        businessName: "Zen Spa & Wellness",
        title: "Full Body Thai Massage",
        description: "Relax and rejuvenate with our signature 60-minute Thai aromatic massage therapy.",
        originalPrice: 3000,
        discountedPrice: 2100,
        discount: "Flat 30% OFF",
        validity: "Until Feb 28, 2026",
        location: "Worli",
        distance: "2.1 km",
        phone: "+91-99887-66554",
        views: 980,
        image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop",
      },
      {
        businessName: "Urban Trends",
        title: "Summer Collection Sale",
        description: "Exclusive BOGO offer on all summer apparel including shirts, dresses, and accessories.",
        originalPrice: 1800,
        discountedPrice: 900,
        discount: "Buy 1 Get 1",
        validity: "Weekend Special Only",
        location: "Phoenix Mall",
        distance: "1.4 km",
        phone: "+91-91234-56789",
        views: 2300,
        image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&h=400&fit=crop",
      },
      {
        businessName: "The Grand Kitchen",
        title: "Premium Dinner Buffet",
        description: "All-you-can-eat dinner buffet with live counters, desserts bar, and mocktails.",
        originalPrice: 2200,
        discountedPrice: 1320,
        discount: "Flat 40% OFF",
        validity: "Mon - Thu only",
        location: "Andheri West",
        distance: "3.2 km",
        phone: "+91-98112-33445",
        views: 1540,
        image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600&h=400&fit=crop",
      },
      {
        businessName: "FitLife Gym",
        title: "Annual Membership Offer",
        description: "Join now and get 3 months free with any annual membership plan. Limited slots.",
        originalPrice: 18000,
        discountedPrice: 12000,
        discount: "3 Months Free",
        validity: "Until Mar 31, 2026",
        location: "Bandra",
        distance: "1.8 km",
        phone: "+91-99001-22334",
        views: 870,
        image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop",
      },
      {
        businessName: "Artisan Chocolates",
        title: "Valentine Special Gift Box",
        description: "Handcrafted Belgian chocolates in a premium gift box. Perfect for gifting.",
        originalPrice: 1200,
        discountedPrice: 849,
        discount: "Flat 30% OFF",
        validity: "Feb 10 - Feb 20, 2026",
        location: "Juhu",
        distance: "4.5 km",
        phone: "+91-88776-55443",
        views: 650,
        image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&h=400&fit=crop",
      },
    ],
  },
  footer: {
    privacy: "Privacy",
    terms: "Terms",
    aboutUs: "About Us",
    contactUs: "Contact Us",
    copyright: `© ${new Date().getFullYear()} BasAaj. All rights reserved.`,
  },
  login: {
    title: "Login / Sign up",
    mobileLabel: "Mobile Number",
    mobilePlaceholder: "Enter your mobile number",
    next: "NEXT",
    brandTagline: "Explore exciting deals & offers around you",
  },
  otp: {
    title: "Verify OTP",
    subtitle: "We've sent a 6-digit code to",
    placeholder: "Enter OTP",
    verify: "VERIFY",
    resend: "Resend OTP",
    didntReceive: "Didn't receive the code?",
  },
  profileSetup: {
    title: "Set Up Your Profile",
    subtitle: "Tell us a bit about yourself to get started.",
    profileImage: "Profile Photo",
    uploadImage: "Upload Photo",
    changeImage: "Change",
    businessNameLabel: "Business Name",
    businessNamePlaceholder: "Enter your business name",
    locationLabel: "Your Location",
    changeLocation: "Change",
    done: "CONTINUE",
  },
  home: {
    offersIn: "Offers in",
    showingResults: "Showing {count} results",
    breadcrumbHome: "Home",
    postOffer: "Post Offer",
    manageListings: "Manage Listings",
    active: "Active",
    views: "Views",
    claims: "Claims",
    searchWithin: "Search within {location}...",
    noOffers: "No offers found nearby. Be the first to post!",
    offers: [
      {
        title: "Luxury Fine Dining Experience",
        location: "The Grand Kitchen, Sector 5",
        discount: "Flat 50% OFF",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
      },
      {
        title: "Handmade Pasta Special",
        location: "Italiano Bistro, MG Road",
        discount: "Free Dessert",
        image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600&h=400&fit=crop",
      },
      {
        title: "Premium Shopping Mall",
        location: "City Centre Mall, Ring Road",
        discount: "Buy 1 Get 1",
        image: "https://images.unsplash.com/photo-1519567241046-7f570f0e4503?w=600&h=400&fit=crop",
      },
      {
        title: "Cozy Cafe & Lounge",
        location: "Brew House, Park Street",
        discount: "Your Listing",
        image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&h=400&fit=crop",
      },
      {
        title: "Relaxing Spa Treatment",
        location: "Serenity Spa, Lake View",
        discount: "30% OFF",
        image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop",
      },
      {
        title: "Artisan Chocolate Collection",
        location: "Sweet Treats, Market Road",
        discount: "Flat \u20B9100 OFF",
        image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&h=400&fit=crop",
      },
    ],
  },
  profilePage: {
    title: "Profile Settings",
    publicProfile: "Public Profile",
    editDetails: "Edit Details",
    saveChanges: "Save Changes",
    email: "Email (Optional)",
    phone: "Phone",
    businessName: "Business Name",
    location: "Location",
    manageAddresses: "Manage Addresses",
    addNewAddress: "+ Add New Address",
    addressLabel: "Address Label",
    addressName: "Full Name",
    addressPhone: "Phone Number",
    addressLine: "Full Address",
    home: "Home",
    work: "Work",
    other: "Other",
    deleteAddress: "Delete Address",
    deleteAddressConfirm: "Are you sure you want to delete this address?",
    signOut: "Sign Out",
    languagePreferences: "Language Preferences",
    languageSubtitle: "Choose the language you want to see content in.",
    english: "English",
    hindi: "Hindi",
  },
  common: {
    loading: "Loading...",
    error: "Something went wrong. Please try again.",
    noData: "No data available.",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    submit: "Submit",
    back: "Back",
    next: "Next",
  },
} as const;
